### ISSUE TITLE
How do I release Lock?

### ISSUE THREAD

**Issue by ssk** [baygeldin/tantiny#5]
I got this error:

Tantiny::TantivyError (Failed to acquire Lockfile: LockBusy. Some("Failed to acquire index lock. If you are using a regular directory, this means there is already an `IndexWriter` working on this `Directory`, in this process or in a different process."))

How can I release the lock?

**Comment by baygeldin** [comment]
If you want to to release the lock you can delete Tantivy's lockfile (`.tantivy-writer.lock`) which is located in index folder.
